FROM ghcr.io/cross-rs/x86_64-unknown-linux-gnu:latest
RUN apt-get update && \
    apt-get install --assume-yes --no-install-recommends make wget librocksdb-dev libsnappy-dev liblz4-dev libzstd-dev libssl-dev pkg-config clang protobuf-compiler
